version: '3.1'

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    ports:
      - $MONGO_PORT:$MONGO_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - $MONGO_EXPRESS_PORT:$MONGO_EXPRESS_PORT
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_EXPRESS_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_EXPRESS_PASSWORD
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo:$MONGO_PORT/
    depends_on:
      - mongo

  postgres:
    image: "postgres:14.5-alpine"
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /data/redis-data:/data

volumes:
  data:
  mongodb_data:
  mongodb_config:
