version: '3.1'

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_NOTEFLOW_USERNAME: ${MONGO_NOTEFLOW_USERNAME}
      MONGO_NOTEFLOW_PASSWORD: ${MONGO_NOTEFLOW_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
  
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      VCAP_APP_PORT: ${MONGO_EXPRESS_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}
    depends_on:
      - mongo

  postgres:
    image: "postgres:14.5-alpine"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  redis:
    image: redis:7.0
    restart: always
    volumes:
      - /data/redis-data:/data

volumes:
  data:
  mongodb_data:
  mongodb_config:
